name: publish

on:
  push:
    branches: ['release']

env:
  REGISTRY: ghcr.io

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DEST: ${{ env.REGISTRY }}/${{ github.actor }}/${{ github.repository }}:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        run: |
             docker build . --tag ${{ env.DEST }}
             docker run ${{ env.DEST }}
             docker push ${{ env.DEST }}
