name: publish

on:
  push:
    branches: ['master']
  repository_dispatch:
    types: [dotfiles_update]
  schedule:
    # midnightly
    - cron: '0 0 * * *'

env:
  REGISTRY: ghcr.io
  VERSION: latest

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        run: |
          docker build . --tag "${REGISTRY}/${GITHUB_REPOSITORY}:${VERSION}"
          docker push "${REGISTRY}/${GITHUB_REPOSITORY}:${VERSION}"
